FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /source

COPY . .
RUN dotnet restore "O2.Services.Certificates.API.sln"
WORKDIR /source/O2.Services.Certificates.API
RUN dotnet build O2.Services.Certificates.API.csproj -c Release -o /app



FROM build AS publish
COPY . .
WORKDIR /source/O2.Services.Certificates.API
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
# COPY --from=build /src/Services/Catalog/Catalog.API/Proto /app/Proto
# COPY --from=build /src/Services/Catalog/Catalog.API/eshop.pfx .
ENTRYPOINT ["dotnet", "O2.Services.Certificates.API.dll"]
